### PR TITLE
Only build uWSGI on Debian

### PR DESCRIPTION
**Pull request by JayH5**
See #28

### CODE REVIEW

**Comment by JayH5** [comment]
The trick with multiple requirements files here was originally built in #14 and then we stopped using it for a bit as it wasn't needed.

**Comment by smn** [comment]
So if we're using uWSGI we cannot use the alpine container?

Do we need to README that somewhere?

**Comment by smn** [comment]
:+1: though

**Comment by JayH5** [comment]
@smn: The builds fail _sometimes_.. The compiled latest version of uWSGI is already in our package index so for most people this won't make a difference. But afaik, nobody is using uWSGI in any containers based on these images yet.

The only documentation of the list of packages we build here _is_ the requirements files here. This repo itself is kind of the best documentation there is about this stuff so not sure where else to document.

**Pull request merged**
