### PR TITLE
uWSGI build on Alpine/cPython 3.5 is flaky

### PR DESCRIPTION
**Pull request by JayH5**
When it crashes it has the message:
`gcc: error trying to exec 'cc1': execvp: No such file or directory`

But it doesn't always crash...

### CODE REVIEW

**Comment by JayH5** [comment]
unbit/uwsgi#1318

**Comment by jerith** [comment]
Do we know what the probability of failure here is? Could we retry a few times on failure to increase the odds of success?

**Comment by JayH5** [comment]
@jerith: no not really, but it's pretty often.. maybe half the time.

At the moment this whole thing is basically just `pip wheel -r requirements.txt`, which fails if one package fails to be built. I guess we could add a `travis_retry` or something... That might increase build times a lot when something goes wrong, though, as pip just wheel's stuff one-by-one, whether or not a wheel has been built already or not.

**Comment by jerith** [comment]
We could probably use `pip download` to fetch the existing wheels and only build the ones we don't get, but that seems complicated. Bleh.

:+1:

**Pull request merged**
